---
branches:
  - main
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
ci: true
tagFormat: "v${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"

verifyConditions:
  - "@semantic-release/changelog"
  - '@semantic-release/git'
  - "@semantic-release/github"
analyzeCommits:
  - path: "@semantic-release/commit-analyzer"
#    releaseRules:
#      - type: "feat"
#        release: "minor"
#      - type: "hotfix"
#        release: "patch"
#      - type: "fix"
#        release: "patch"
#      - type: "patch"
#        release: "patch"
#      - type: "minor"
#        release: "minor"
#      - type: "breaking"
#        release: "major"
generateNotes:
  - path: "@semantic-release/release-notes-generator"
    writerOpts:
      groupBy: "type"
      commitGroupsSort:
        - "title" # Sort by title
        - "feat" # Sort "feat" first
        - "fix" # Then sort "fix"
        - "chore" # Then sort "chore"
        - "docs" # Then sort "docs"
        - "refactor" # Then sort "refactor"
      commitsSort: "header"
      linkCompare: true
      linkReferences: true
    #    types:
    #      - type: "feat"
    #        section: "Features"
    #      # Tracked bug fix with a hotfix branch
    #      - type: "hotfix"
    #        section: "Bug Fixes"
    #      # Uninmportent fix (CI testing, etc)
    #      - type: "fix"
    #        section: "Bug Fixes"
    #      - type: "chore"
    #        section: "Chores"
    #      - type: "doc"
    #        section: "Chores"
    #      - type: "style"
    #        hidden: true
    #      - type: "refactor"
    #        hidden: true
    #      - type: "perf"
    #        hidden: true
    #      - type: "test"
    #        hidden: true
    presetConfig: true
prepare:
  - path: "@semantic-release/changelog"
  - path: "@semantic-release/git"
    message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    assets:
      - "CHANGELOG.md"
      - "README.md"
#      - "artifacts/*"
      - "artifacts/**/*"

publish:
  - path: "@semantic-release/github"
    assets:
      - "CHANGELOG.md"
      - "README.md"
#      - "artifacts/*"
      - "artifacts/**/*"

success:
  - "@semantic-release/github"

fail:
  - "@semantic-release/github"